### ISSUE TITLE
Vim `completeopt`'s `noselect` doesn't work

### ISSUE THREAD

**Issue by haze** [Shougo/ddc.vim#104]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

I followed the documentation to setup `ddc.vim`, and the FAQ section about "auto select behavior" says to use `set completeopt+=noselect`.

As seen in the image, even with this option set (I ran `:set completeopt`), the first popup menu item is not selected.
![image](https://user-images.githubusercontent.com/15584994/196570840-0968a153-beaf-4f87-89ff-6c7fa6c30ee6.png)

## Expected

The first popup menu item to be selected (auto select behavior)

## Environment Information

- ddc.vim version (SHA1): `d9111bd83986c2cac588e123b3bfe357bec34509`

- denops.vim version (SHA1): `53ce6187e04da044c85b79ef856f1487326a7ac5`

- deno version(`deno -V` output): `deno 1.26.1`

- OS: macOS 13 Ventura

- neovim/Vim `:version` output:
```
:version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Oct  8 2022 19:49:40)
macOS version - arm64
Included patches: 1-696
Compiled by haze@202210081949/89e86cc7e
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +clipboard         +dnd               +fullscreen        +lispindent        +mouse_sgr         +persistent_undo   +smartindent       +terminal          +viminfo           -xsmp
-arabic            +cmdline_compl     -ebcdic            -gettext           +listcmds          -mouse_sysmouse    +popupwin          -sodium            +terminfo          +virtualedit       -xterm_clipboard
+autocmd           +cmdline_hist      +emacs_tags        -hangul_input      +localmap          +mouse_urxvt       +postscript        +sound             +termresponse      +visual            -xterm_save
+autochdir         +cmdline_info      +eval              +iconv             +lua/dyn           +mouse_xterm       +printer           +spell             +textobjects       +visualextra
-autoservername    +comments          +ex_extra          +insert_expand     +menu              +multi_byte        +profile           +startuptime       +textprop          +vreplace
+balloon_eval      +conceal           +extra_search      +ipv6              +mksession         +multi_lang        -python            +statusline        +timers            +wildignore
+balloon_eval_term +cryptv            -farsi             +job               +modify_fname      -mzscheme          -python3           -sun_workshop      +title             +wildmenu
+browse            -cscope            +file_in_path      +jumplist          +mouse             +netbeans_intg     +quickfix          +syntax            +toolbar           +windows
++builtin_terms    +cursorbind        +find_in_path      +keymap            +mouseshape        +num64             +reltime           +tag_binary        +transparency      +writebackup
+byte_offset       +cursorshape       +float             +lambda            +mouse_dec         +odbeditor         -rightleft         -tag_old_static    +user_commands     -X11
+channel           +dialog_con_gui    +folding           +langmap           -mouse_gpm         +packages          -ruby              -tag_any_white     +vartabs           -xfontset
+cindent           +diff              -footer            +libcall           -mouse_jsbterm     +path_extra        +scrollbind        -tcl               +vertsplit         +xim
+clientserver      +digraphs          +fork()            +linebreak         +mouse_netterm     -perl              +signs             +termguicolors     +vim9script        -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe -DMACOS_X -DMACOS_X_DARWIN -g -O2 -arch arm64 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -arch arm64 -L/usr/local/lib -o Vim -lm -lncurses -liconv -framework AppKit

```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
call ddc#custom#patch_global('sources', ['vim-lsp'])
call ddc#custom#patch_global('sourceOptions', {
  \ 'vim-lsp': {
  \   'matchers': ['matcher_fuzzy'],
  \   'mark': 'lsp',
  \ }})

set completeopt+=noselect

" Use ddc.
call ddc#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Get any completion, the first item is not selected when the popup menu shows up

**Comment by Shougo** [comment]
Your vimrc is not minimal.  Especially, `pum.vim` is already installed?

It is important.

**Comment by haze** [comment]
Not sure what you mean by that. If you think that I face this issue because the provided vimrc is missing things, it's not. that's the exact file I used. I have both denops and ddc.vim installed in `.vim/pack/haze/start`, nothing more than that and the vimrc. I do not have pum.vim installed. When I did have it installed, it created odd overlaps with another popup menu and behaved oddly, so I removed it. Do you suggest I re-add it? Please let me know if theres anything else I can provide. Thanks for your hard work on this plugin in advance!

**Comment by Shougo** [comment]
Your vimrc does not add runtimepath.  It is very very hard to understand your vimrc.

**Comment by Shougo** [comment]
I get it..  Please use `set completeopt+=noinsert` instead.

**Comment by Shougo** [comment]
Please see the documentation correctly.

```
Q: I want to use the auto select feature.

A: You can use it by the 'completeopt' option. >

	set completeopt+=noinsert
```

This is `noselect`??

**Comment by haze** [comment]
I've changed my minimal vimrc to use `noinsert` instead and I still see the same behavior.

**Comment by Shougo** [comment]
> When I did have it installed, it created odd overlaps with another popup menu and behaved oddly, so I removed it (the requirements of ddc.vim don't list pum.vim as a hard requirement). 

It is another problem.  Please create the new issue with `minimal vimrc`.

**Comment by Shougo** [comment]
Oh, no.  You have tested `.gvimrc`...
Please change `.vimrc` instead.

I think you don't know `vim -u vimrc`.

**Comment by Shougo** [comment]
And you should check `completeopt` value by `verbose set completeopt?`.

**Comment by haze** [comment]
> And you should check `completeopt` value by `verbose set completeopt?`.

Thank you so much! This helped me figure out what was overriding my `completeopt`. I also had `asyncomplete` installed. Sorry for wasting your time, but thanks for teaching me something new :)

**Comment by Shougo** [comment]
Oh, no...

So I have said `I think you have not test the minimal vimrc`.
