### ISSUE TITLE
`ddc#syntax#get()` return always `[]` on latest neovim

### ISSUE THREAD

**Issue by uplus** [Shougo/ddc.vim#106]
# Problems summary

`ddc#syntax#get()` return always `[]` on latest neovim.

For example, `ddc#syntax#get()` return `[]` on this yaml file.

```hoge.yaml
key: value
```

```vim
echo ddc#syntax#get() " return []
```

This problem occurred in same filetypes other than YAML(Ruby, Scala, etc..).
It seems that Treesitter's behavior or interface has changed.

## Expected

`ddc#syntax#get()` return not empty value.

For example, `ddc#syntax#get()` return `['String', 'Identifier']` on this yaml file.

```hoge.yaml
key: value
```

```vim
echo ddc#syntax#get() " return `['String', 'Identifier']` 
```

## Environment Information

- ddc.vim version (SHA1): https://github.com/Shougo/ddc.vim/commit/d9111bd
  - 2022-10-18

- denops.vim version (SHA1): `17030b4`

- deno version(`deno -V` output): `deno 1.26.1`

- OS: 6.0.1-arch2-1

- neovim/Vim `:version` output:
  - NVIM v0.9.0-dev-152+g1887d8d7d
  - https://github.com/neovim/neovim/commit/1887d8d7d

### Neovim commit hash history

- :x: https://github.com/neovim/neovim/commit/1887d8d7d
  - latest version on 2022/10/23
  - This problem is occurring. 
- :x: https://github.com/neovim/neovim/commit/2ecb407
  - Probably this problem was occurred by this merge commit.
  - https://github.com/neovim/neovim/pull/19931
- :o: https://github.com/neovim/neovim/commit/06d5c63
  - One previous merge commit for "2ecb407".
  - This problem did not occur.

There seems to have been a breaking change in treesitter's behaviour, but I don't know the details.

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/ddc.vim
set runtimepath+=~/.cache/dein/repos/github.com/nvim-treesitter/nvim-treesitter
set runtimepath+=~/.cache/dein/repos/github.com/vim-denops/denops.vim

call ddc#enable()

lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = { enable = true }
}
EOF

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `nvim 'hoge.yaml'`
2. Move cursor any position.
3. `:echo ddc#syntax#get()`

**Comment by Shougo** [comment]
Too bad.
