### ISSUE TITLE
Regression: `<C-f>` is appended to `indentkeys`

### ISSUE THREAD

**Issue by e-kwsm** [Shougo/ddc.vim#109]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
If I insert a word that ends with `do`—`do`, `sudo`, or `todo`—in a shell file, then `<C-f>` is appended.

This bisects to e54a5c674d9107c886c3cf8e39a9f6394645f9b8 (#105; the revisions of the other plugins shown below are pinned).

## Expected
`<C-f>` is not appended.

## Environment Information

- ddc.vim version (SHA1): a26cb54090646f49282b3c8edfb1d7426b5d4a86
- denops.vim version (SHA1): vim-denops/denops.vim@53ce6187e04da044c85b79ef856f1487326a7ac5
- ddc-source-around: Shougo/ddc-source-around@0a4a62a64cdcf478ed3645e8da69c1198802f71b
- ddc-ui-native: Shougo/ddc-ui-native@9c7bb46cb01f224331e142fea2e0d45cdd7de7bb
- deno version(`deno -V` output): deno 1.27.0
- OS: Debian 11.5
- neovim/Vim `:version` output: v0.9.0-dev-206+gc3aba403c

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath-=~/.config/nvim
set runtimepath-=~/.config/nvim/after
set runtimepath-=~/.local/share/nvim/site
set runtimepath-=~/.local/share/nvim/site/after

set runtimepath+=path/to/denops.vim
set runtimepath+=path/to/ddc.vim
set runtimepath+=path/to/ddc-source-around
set runtimepath+=path/to/ddc-ui-native

call ddc#custom#patch_global('ui', 'native')
call ddc#custom#patch_global('sources', ['around'])

call ddc#enable()

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `nvim -u vimrc -c 'setf sh'`
2. insert `sudo`

## Screenshot (if possible)
![sudo](https://user-images.githubusercontent.com/11627708/199218163-b4eef262-364d-446e-9852-37ceffa776ce.gif)

**Comment by e-kwsm** [comment]
Also happens with the following reserved words

- `elif`
- `else`
- `esac`
- `fi`
- `then`

but does not with

- `case`
- `for`
- `if`
- `in`
- `until`
- `while`

**Comment by Shougo** [comment]
Oh, the indentation is broken.

**Comment by e-kwsm** [comment]
`<C-f>` is appended to one of `indentkeys`: this also happens with `elif` and `except` in Python.

**Comment by Shougo** [comment]
Fixed.  Please update `ddc-ui-native`.

**Comment by e-kwsm** [comment]
Thank you.
