### ISSUE TITLE
cmdline: onCompleteDone() is not called when select item by pum#map#select_relative().

### ISSUE THREAD

**Issue by Milly** [Shougo/ddc.vim#113]
# Problems summary

`source.onCompleteDone()` is not called when select item by `pum#map#select_relative()`.

It is fine when select item by `pum#map#insert_relative()`.

## Expected

`source.onCompleteDone()` is called both.

Or, document to `pum#map#select_relative()` is not usable in cmdline-mode.

## Environment Information

- ddc.vim version (SHA1): e338c37
- ddc-ui-pum version (SHA1): Shougo/ddc-ui-pum@298e605
- pum.vim version (SHA1): Shougo/pum.vim@43f585f
- denops.vim version (SHA1): vim-denops/denops.vim@448f84c
- deno version(`deno -V` output):
  ```
  deno 1.28.1
  ```
- Environment 1:
  - OS: Windows 10 22H2 19045.2251
  - neovim/Vim `:version` output:
    ```
    VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 14 2022 23:33:49)
    MS-Windows 64 ビット GUI 版 with OLE サポート
    適用済パッチ: 1-883
    ```
- Environment 2:
  - OS: Ubuntu 18.04 LTS
  - neovim/Vim `:version` output:
    ```
    VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 24 2022 03:43:18)
    Included patches: 1-929
    ```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" minimum vimrc
set nocompatible

set rtp^=path/to/denops.vim
set rtp^=path/to/ddc.vim
set rtp^=path/to/ddc-ui-pum
set rtp^=path/to/pum.vim
set rtp^=path/to/testdir

call ddc#custom#patch_global(#{
\ autoCompleteEvents: ['CmdlineChanged'],
\ ui: 'pum',
\ sources: ['test'],
\ cmdlineSources: {':': ['test']},
\})
call ddc#enable()

nnoremap : <Cmd>call ddc#enable_cmdline_completion()<CR>:

cnoremap <silent> <C-J> <Cmd>call pum#map#select_relative(+1)<CR>
cnoremap <silent> <C-N> <Cmd>call pum#map#insert_relative(+1)<CR>
cnoremap <silent> <C-Y> <Cmd>call pum#map#confirm()<CR>

" testing
function! TestSelect() abort
  echomsg "use select_relative"
  call feedkeys(":test")
  call timer_start(500,  {-> feedkeys("\<C-J>\<C-Y>\<Esc>", 't')})
endfunction
function! TestInsert() abort
  echomsg "use insert_relative"
  call feedkeys(':test')
  call timer_start(500,  {-> feedkeys("\<C-N>\<C-Y>\<Esc>", 't')})
endfunction
call timer_start(3000, {-> TestSelect()})
call timer_start(5000, {-> TestInsert()})
call timer_start(7000, {-> TestInsert()})
call timer_start(9000, {-> TestSelect()})
```

```typescript
// &rtp/denops/@ddc-sources/test.vim
import { BaseSource, Item } from "https://deno.land/x/ddc_vim@v3.1.0/types.ts";

type Params = Record<string, never>;
type UserData = {foo: string;};

export class Source extends BaseSource<Params, UserData> {
  override params(): Params {
    return {};
  }
  override async gather(): Promise<Item<UserData>[]> {
    return [{word: 'testword', user_data: {foo: 'bar'}}];
  }
  override async onCompleteDone({userData}: {userData: UserData}): Promise<void> {
    console.error('test: onComleteDone()', userData);
  }
}
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Run `vim -u vimrc`.
2. Wait testing done (10 seconds).
3. Execute command `:messages`.

### Actual messages

```
use select_relative
use insert_relative
[denops] test: onComleteDone() { foo: "bar" }
use insert_relative
[denops] test: onComleteDone() { foo: "bar" }
use select_relative
```

### Expected messages

```
use select_relative
[denops] test: onComleteDone() { foo: "bar" }
use insert_relative
[denops] test: onComleteDone() { foo: "bar" }
use insert_relative
[denops] test: onComleteDone() { foo: "bar" }
use select_relative
[denops] test: onComleteDone() { foo: "bar" }
```

## Question

<del>`pum#map#insert_relative()` in cmdline-mode doesn't "insert" strings, isn't that what "select" does?</del>

"insert" was working correctly. I think it is because `<silent>` was attached.

**Comment by Milly** [comment]
Sorry test vimrc may have been wrong.
`<silent>` should **NOT** be used in `cmap`?

**Comment by Milly** [comment]
I change mappings to:
```vim
cnoremap <C-J> <Cmd>call pum#map#select_relative(+1)<CR>
cnoremap <C-N> <Cmd>call pum#map#insert_relative(+1)<CR>
cnoremap <C-Y> <Cmd>call pum#map#confirm()<CR>
```

And the behavior has changed so that `[denops] test: onComleteDone() { foo: "bar" }` is completely not displayed. The opposite of the expected behavior.

**Comment by Shougo** [comment]
It is not the problem of `ddc.vim`.  It is the problem of `pum.vim`.

**Comment by Shougo** [comment]
Fixed.  Please update `pum.vim`.
