### ISSUE TITLE
README.md instructions gives `Undefined variable: around`

### ISSUE THREAD

**Issue by grhkm21** [Shougo/ddc.vim#117]
# Problems summary

I am quite new to vim plugins in general, so sorry if I am doing something stupid. I used the README.md settings under "Configuration", and it seems to work, but everytime I start editing a file it gives an error

```
E121: Undefined variable: around
E116: Invalid arguments for function ddc#custom#patch_filetype
```

## Environment Information

(Sorry if I did these wrong, but I followed [this](https://superuser.com/a/1717032/1698620))

- ddc.vim version (SHA1): 73c43fb7129eea859b85789b7c61d9781861ebbb

- denops.vim version (SHA1): ec67c68cbc5eec720a34749479f053b46c8c9f07

- deno version(`deno -V` output): 1.29.1

- OS: Mac

- neovim/Vim `:version` output: NVIM v0.9.0-dev-546+g98daaa798

## Expected

No error. (But the autocomplete part works fine! I can press tab to select them as well)

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

I am not sure how to not use plugin managers...

```vim
call plug#begin()

Plug 'Shougo/ddc.vim'
Plug 'vim-denops/denops.vim'

Plug 'Shougo/ddc-ui-native'
Plug 'Shougo/ddc-source-around'
Plug 'Shougo/ddc-matcher_head'
Plug 'Shougo/ddc-sorter_rank'

call plug#end()

" Customize global settings

" You must set the default ui.
" Note: native ui
" https://github.com/Shougo/ddc-ui-native
call ddc#custom#patch_global('ui', 'native')

" Use around source.
" https://github.com/Shougo/ddc-source-around
call ddc#custom#patch_global('sources', ['around'])

" Use matcher_head and sorter_rank.
" https://github.com/Shougo/ddc-matcher_head
" https://github.com/Shougo/ddc-sorter_rank
call ddc#custom#patch_global('sourceOptions', #{
      \ _: #{
      \   matchers: ['matcher_head'],
      \   sorters: ['sorter_rank']},
      \ })

" Change source options
call ddc#custom#patch_global('sourceOptions', #{
      \   around: #{ mark: 'A' },
      \ })
call ddc#custom#patch_global('sourceParams', #{
      \   around: #{ maxSize: 500 },
      \ })

" Customize settings on a filetype
call ddc#custom#patch_filetype(['c', 'cpp'], 'sources',
      \ ['around', 'clangd'])
call ddc#custom#patch_filetype(['c', 'cpp'], 'sourceOptions', #{
      \   clangd: #{ mark: 'C' },
      \ })
call ddc#custom#patch_filetype('markdown', 'sourceParams', {
      \   around: #{ maxSize: 100 },
      \ })

" Mappings

" <TAB>: completion.
inoremap <silent><expr> <TAB>
\ pumvisible() ? '<C-n>' :
\ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
\ '<TAB>' : ddc#map#manual_complete()

" <S-TAB>: completion back.
inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'

" Use ddc.
call ddc#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Run `nvim file`
2. ...

## Screenshot (if possible)

<img width="547" alt="Screenshot 2022-12-23 at 20 19 08" src="https://user-images.githubusercontent.com/83517584/209402247-76d26c78-0b28-4cc7-90b3-2ca0df33657d.png">

https://asciinema.org/a/2uPF3Senm49xUrGHukWwhxXiC

## Log messages

:message

```
Error detected while processing /Users/grhkm/.config/nvim/init.vim:
line   47:
E121: Undefined variable: around
E116: Invalid arguments for function ddc#custom#patch_filetype
E475: Invalid argument:
```

**Comment by Shougo** [comment]
One line is wrong.  It must be:

```vim
call ddc#custom#patch_filetype('markdown', 'sourceParams', #{
      \   around: #{ maxSize: 100 },
      \ })
```

> I am quite new to vim plugins in general, so sorry if I am doing something stupid. I used the README.md settings under "Configuration", and it seems to work, but everytime I start editing a file it gives an error

I have checked the example in the documentation.  It is right.
So this is your copy-and-paste miss.
