### ISSUE TITLE
References ddc#custom#set_global() circulation.

### ISSUE THREAD

**Issue by hokorobi** [Shougo/ddc.vim#118]
"The {dict} is the same as for ddc#custom#set_global(). " is writtern in description of ddc#custom#set_global()

https://github.com/Shougo/ddc.vim/blob/73c43fb7129eea859b85789b7c61d9781861ebbb/doc/ddc.txt#L389-L391

**Comment by Shougo** [comment]
Fixed.

**Comment by hokorobi** [comment]
Thank you.
