### ISSUE TITLE
popup items are not refreshed

### ISSUE THREAD

**Issue by chunxuan-hs** [Shougo/ddc.vim#122]
# Problems summary
dd.vim do not eliminate not matched items.  Not sure if there are something wrong with ddc updates or I have messed up my cofig again.

## Expected
If the the strings do not match requirement, they will be removed from the pop up. 
## Environment Information

- ddc.vim version (SHA1):
latest

- denops.vim version (SHA1):
latest

- deno version(`deno -V` output):
deno 1.33.2

- OS:
mac

- neovim/Vim `:version` output:
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
call ddc#custom#patch_global('ui', 'native')

call ddc#custom#patch_global('sources', ['around'])

call ddc#custom#patch_global('sourceOptions', #{
      \ _: #{
      \   matchers: ['matcher_head'],
      \   sorters: ['sorter_rank']},
      \ })

" Change source options
call ddc#custom#patch_global('sourceOptions', #{
      \   around: #{
      \     mark: 'A',
      \     isVolatile: v:true},
      \ })

call ddc#custom#patch_global('sourceParams', #{
      \   around: #{ maxSize: 500 },
      \ })

inoremap <silent><expr> <TAB>
\ pumvisible() ? '<C-n>' :
\ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
\ '<TAB>' : ddc#map#manual_complete()

" <S-TAB>: completion back.
inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'

set completeopt+=noinsert
call ddc#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)
type the something and pop up will never refresh.

## Screenshot (if possible)
As dattt do not match anything in the text, the popup should be empty. And it worked like that before.
<img width="157" alt="Screenshot 2023-05-11 at 21 25 27" src="https://github.com/Shougo/ddc.vim/assets/132476141/60725a8e-c81b-4459-9c7a-36ae3e5af4ec">

**Comment by Shougo** [comment]
Fixed.  Please update `ddc-ui-native`.
