### ISSUE TITLE
ddc#update_items hides items from other sources

### ISSUE THREAD

**Issue by ibuki2003** [Shougo/ddc.vim#123]
# Problems summary

When `ddc#update_items` was called, items from other sources disappear.

## Expected

all items should be kept shown even after updated

## Environment Information

- ddc.vim version (SHA1): 0c51181be212647a7f9de21727ce293fe2f5d5b7

- denops.vim version (SHA1): 3b489d50ba2e034c829a09475a4002176bffbef7

- deno version(`deno -V` output): deno 1.33.2

- OS: ArchLinux `6.3.4-arch1-1`

- neovim/Vim `:version` output:
  NVIM v0.9.0
  Build type: Release
  LuaJIT 2.1.0-beta3

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

<details>
<summary>init.vim</summary>

```vim
" below is just a list of plugins. no matter which manager is used.
call plug#begin()

Plug 'Shougo/ddc.vim'
Plug 'vim-denops/denops.vim'

Plug 'Shougo/ddc-ui-pum'
Plug 'Shougo/pum.vim'

Plug 'Shougo/ddc-source-around'
Plug 'matsui54/ddc-dictionary'

call plug#end()

call ddc#custom#patch_global('ui', 'pum')

call ddc#custom#patch_global('sources', ['around', 'dictionary'])

call ddc#custom#patch_global('sourceOptions', { '_': {
      \ 'minAutoCompleteLength' : 1,
      \}})

call ddc#custom#patch_global('sourceOptions', { 'around' : {
      \ 'matchers' : [],
      \ 'minAutoCompleteLength' : 0,
      \}})

call pum#set_option({ 'use_complete': v:true })


call ddc#custom#patch_global('sourceParams', { 'dictionary': {
      \ 'dictPaths': ['/usr/share/dict/words'],
      \ 'isVolatile': v:true,
      \ }
      \ })
call ddc#custom#patch_global('sourceOptions', { 'dictionary': {'mark': 'D'}, })


call ddc#enable()

inoremap <silent><expr> <TAB> ddc#map#manual_complete()
inoremap <C-e>   <Cmd>call pum#map#cancel()<CR>
```
</details>

<details>
<summary>modified ddc-source-around, so that it returns items asynchronously</summary>

```typescript
// original source from https://github.com/Shougo/ddc-source-around/blob/main/denops/%40ddc-sources/around.ts
import { BaseSource, } from "https://deno.land/x/ddc_vim@v3.4.0/types.ts";
import { DdcGatherItems } from "https://deno.land/x/ddc_vim@v3.4.0/types.ts";
import { Denops, } from "https://deno.land/x/ddc_vim@v3.4.0/deps.ts";

type Params = { maxSize: number; };

export class Source extends BaseSource<Params> {
  override async gather(args: {
    denops: Denops;
  }): Promise<DdcGatherItems> {
    setTimeout(async () => {
      console.log(this.name);
      await args.denops.call("ddc#update_items", this.name, [
        { word: "a" },
        { word: "b" },
        { word: "c" },
      ]);
    }, 1000);
    return await Promise.resolve({
      items: [],
      isIncomplete: true,
    });
  }

  override params(): Params {
    return { maxSize: 200, };
  }
}
```
</details>

## How to reproduce the problem from neovim/Vim startup (Required!)

1. move to the cursor at the start of a line
2. enter insert mode
3. `<C-e>` to close pum
4. press `<Tab>` to fire manual_complete
5. at first items from `dictionary` are shown but 1s later `around` ones appear and `dictionary` disappear.

## Additional information

the requirements for reproducing are:
- ui-pum with `'use_complete': v:true` or `'insert': v:true`
- manual_complete
- minAutoCompleteLength is 0
    - it seems that items only from `'minAutoCompleteLength': 0` are shown after `update_items` is called.
- cursor is not after alphabets (i.e. not in words)

## Screenshot (if possible)

https://github.com/Shougo/ddc.vim/assets/28347743/32a92a03-77de-4ce8-9d34-97012fb31e39

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
Fixed.
