### ISSUE TITLE
onCompleteDone is not fired

### ISSUE THREAD

**Issue by uga-rosa** [Shougo/ddc.vim#126]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
ddc-source's onCompleteDone does not fire in pum#map#confirm().

## Expected
Be fired.

## Environment Information

Latest

- ddc.vim version (SHA1):
4a99c812f24d5f2cd06e31cc9277867e2d58d88d

- denops.vim version (SHA1):
4a99c812f24d5f2cd06e31cc9277867e2d58d88d

- deno version(`deno -V` output):
deno 1.34.3

- OS:
Ubuntu 22.04 (WSL2)

- neovim/Vim `:version` output:
NVIM v0.10.0-dev-3bf887f

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set runtimepath+=/path/to/denops.vim
set runtimepath+=/path/to/ddc.vim
set runtimepath+=/path/to/ddc-ui-pum
set runtimepath+=/path/to/pum.vim

call ddc#custom#patch_global(#{
      \ ui: 'pum',
      \ sources: ['test']
      \})

inoremap <C-n> <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <C-p> <Cmd>call pum#map#insert_relative(-1)<CR>
inoremap <C-y> <Cmd>call pum#map#confirm()<CR>

call ddc#enable()
```

Source for test
- denops/@ddc-sources/test.ts
```typescript
import { BaseSource, DdcGatherItems } from "https://deno.land/x/ddc_vim@v3.7.0/types.ts";
import {
  GatherArguments,
  OnCompleteDoneArguments,
} from "https://deno.land/x/ddc_vim@v3.7.0/base/source.ts";

type Params = Record<string, never>;

export class Source extends BaseSource<Params> {
  gather(
    _args: GatherArguments<Params>,
  ): Promise<DdcGatherItems> {
    return Promise.resolve({
      items: [
        { word: "test1" },
        { word: "test2" },
      ],
      isIncomplete: false,
    });
  }

  onCompleteDone(
    args: OnCompleteDoneArguments<Params>,
  ): Promise<void> {
    console.log(args);
    return Promise.resolve();
  }

  params(): Params {
    return {};
  }
}
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Input `te`.
2. Select a candidate with `<C-n>/<C-p>` and confirm with `<C-y>`.
3. Argument of onCompleteDone is not output

**Comment by Shougo** [comment]
Please see this.

```
					*ddc-source-attribute-onCompleteDone*
onCompleteDone		(function)			(Optional)
		Called after the completion.
		It is useful to substitute text after completion.
		NOTE: |ddc-item-attribute-user_data| must be "UserData" to use
		the feature.
```

`user_data` is needed for the feature.
