### ISSUE TITLE
`SourceOptions.keywordPattern` differs between docs and implementation

### ISSUE THREAD

**Issue by Milly** [Shougo/ddc.vim#127]
# Problems summary

Document says:
```
keywordPattern
		It defines the keyword pattern for completion.
		NOTE: It is JavaScript regexp.
		NOTE: "\k" is converted to 'iskeyword' pattern.
```

But actual value in implementation (e.g. in `Source.gather()`):
```jsonc
{
  "sourceOptions": {
    "keywordPattern": "\\k*",
    // ...
  }
}
```

## Expected

Add a note to the docs that developers should convert it themselves.

As an additional question, can `vimoption2ts()` be used as a public API?
Or it would be nice to have a convenience function that can convert `keywordPattern`.

## Environment Information

- ddc.vim version (SHA1): [4a99c81](https://github.com/Shougo/ddc.vim/commit/4a99c812f24d5f2cd06e31cc9277867e2d58d88d)

- denops.vim version (SHA1): [62b1d22](https://github.com/vim-denops/denops.vim/commit/62b1d22b3e60fcc9e570a531a5af1e4b2393c15a)

- deno version(`deno -V` output): deno 1.34.3

- OS: Windows 11 22H2

- neovim/Vim `:version` output:
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 14 2023 22:47:11)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1632
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

I omitted it because it's a documentation issue.

## How to reproduce the problem from neovim/Vim startup (Required!)

I omitted it because it's a documentation issue.

**Comment by Milly** [comment]
One more point, how about adding `@deprecated` tag to the TSDoc for `Options.keywordPattern`?

**Comment by Shougo** [comment]
Fixed.
