### ISSUE TITLE
FileType onEvent does not fire with `:setf javascript` when cmdline completion is enabled

### ISSUE THREAD

**Issue by uga-rosa** [Shougo/ddc.vim#134]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
SSIA.
This happens when you confirm from the completion menu.

## Expected
onEvent fires.

## Environment Information

latest

- ddc.vim version (SHA1):

- denops.vim version (SHA1):

- deno version(`deno -V` output):

- OS:

- neovim/Vim `:version` output:

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set runtimepath+=/path/to/denops.vim
set runtimepath+=/path/to/ddc.vim
set runtimepath+=/path/to/ddc-ui-pum
set runtimepath+=/path/to/pum.vim
set runtimepath+=/path/to/ddc-filter-matcher_head
set runtimepath+=/path/to/ddc-source-cmdline

call ddc#custom#patch_global(#{
      \ ui: 'pum',
      \ autoCompleteEvents: [
      \  'InsertEnter',
      \  'TextChangedI',
      \  'TextChangedP',
      \  'CmdlineEnter',
      \  'CmdlineChanged',
      \ ],
      \ sourceOptions: #{
      \   _: #{
      \     minAutoCompleteLength: 1,
      \     matchers: ['matcher_head'],
      \   },
      \ },
      \ sources: ['minimal'],
      \ cmdlineSources: {
      \   ':': ['cmdline'],
      \ },
      \})

inoremap <C-n> <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <C-p> <Cmd>call pum#map#insert_relative(-1)<CR>
inoremap <C-y> <Cmd>call pum#map#confirm()<CR>

nnoremap : <Cmd>call ddc#enable_cmdline_completion()<CR>:
cnoremap <C-n> <Cmd>call pum#map#insert_relative(+1)<CR>
cnoremap <C-p> <Cmd>call pum#map#insert_relative(-1)<CR>

call ddc#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Start with `nvim`. The message `[denops] (ddc) event: Initialize` is shown.
2. Open any file (e.g. `:e init.vim`). The message `[denops] (ddc) event: BufEnter` is shown.
3. Select `:setf javascript` from the completion menu and run the Ex command with `<CR>` as is. `[denops] (ddc) event: FileType` should appear, but does not.

FYI: You can avoid this problem by manually typing.

## Screenshot (if possible)
![filetype](https://github.com/Shougo/ddc.vim/assets/82267684/500e8f1d-d50d-4398-9065-0e67215a6527)

**Comment by uga-rosa** [comment]
Sorry. I forgot to paste it.

```typescript
import { OnEventArguments } from "https://deno.land/x/ddc_vim@v3.9.0/base/source.ts";
import { BaseSource, DdcGatherItems } from "https://deno.land/x/ddc_vim@v3.9.0/types.ts";

type Params = Record<never, never>;

export class Source extends BaseSource<Params> {
  events = [
    "Initialize",
    "FileType",
    "BufEnter",
  ];

  gather(): Promise<DdcGatherItems> {
    return Promise.resolve([
      { word: "test1" },
    ]);
  }

  onEvent({
    context,
  }: OnEventArguments<Params>): Promise<void> {
    console.log(`event: ${context.event}`);
    return Promise.resolve();
  }

  params(): Params {
    return {};
  }
}
```

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
Fixed.
