### ISSUE TITLE
Completion is not be fired on post confirm

### ISSUE THREAD

**Issue by KentoOgata** [Shougo/ddc.vim#136]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

```typescript
const foo = {
  bar: 'a',
}
```

On a buffer like above, I want to complete `bar` on `fo<C-n><C-y>.`.

## Expected

Popupmenu will be displayed.

## Environment Information

- ddc.vim version (SHA1): 400afe5cd642362255f63a9cf38c490a2f40f839

- denops.vim version (SHA1): 22e7ae3d712f190b3f46483e6b9dd50a99a9abbd

- deno version(`deno -V` output): deno 1.35.3

- OS: Arch Linux (on WSL2)

- neovim/Vim `:version` output:

    ```
    NVIM v0.10.0-dev-737+gdf2f5e3912
    Build type: Release
    LuaJIT 2.1.0-beta3
    ````

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
const s:packpath = expand('<script>:p:h')
let &packpath = s:packpath
const s:ToPackPath = { name -> s:packpath .. '/pack/github.com/opt/' .. name }

function s:PackAdd(ghrepo) abort
  const plugin = #{
        \ path: s:ToPackPath(a:ghrepo),
        \ repo: a:ghrepo->printf('https://github.com/%s.git'),
        \ name: a:ghrepo,
        \ }
  if !isdirectory(plugin.path)
    call system(['git', 'clone', plugin.repo, plugin.path])
  endif
  exec 'packadd' plugin.name
endfunction

call s:PackAdd('vim-denops/denops.vim')
call s:PackAdd('Shougo/ddc.vim')
call s:PackAdd('Shougo/ddc-ui-native')
call s:PackAdd('Shougo/ddc-source-nvim-lsp')
call s:PackAdd('neovim/nvim-lspconfig')

call ddc#custom#set_global(#{
      \   ui: 'native',
      \   sources: [
      \     #{
      \       name: 'nvim-lsp',
      \       options: #{
      \         forceCompletionPattern: '\.',
      \         minAutoCompleteLength: 1,
      \       },
      \     },
      \   ],
      \ })

call ddc#enable()

lua << EOF
require('lspconfig').denols.setup {}
EOF
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Put above `init.vim`.
2. Start neovim by `$nvim -u ./init.vim test.ts`.
3. Paste below code block to current buffer.

    ```typescript
    const foo = {
      bar: 'a',
    }
    ```

4. Type `fo<C-y>.`.

**Comment by Shougo** [comment]
Fixed.

**Comment by KentoOgata** [comment]
It looks working. Thank you!
