### ISSUE TITLE
matcher should not be applied to converted item

### ISSUE THREAD

**Issue by atusy** [Shougo/ddc.vim#138]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

I want to implement a converter that extracts a part of the original word as a new word.

However, it seems the matcher applies on the new word, not the original word.

## Expected

matchers should be applied to original words from the source.

## Environment Information

- ddc.vim version (SHA1): 6d4ed74

- denops.vim version (SHA1): 22e71e3

- deno version(`deno -V` output): 1.34.3

- OS: Manjaro Linux

- neovim/Vim `:version` output:

```
NVIM v0.10.0-dev-699+gb74262a33
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run ":verbose version" for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=path/to/denops.vim
set rtp+=path/to/ddc.vim
set rtp+=path/to/ddc-ui-native
set rtp+=path/to/ddc-source-line
set rtp+=path/to/ddc-matcher_head
set rtp+=path/to/atusy/ddc-filter-converter_string_match
call ddc#custom#patch_global("ui", "native")
call ddc#custom#patch_global("sources", ["line"])
call ddc#custom#patch_global("sourceOptions", #{ line: #{ matchers: ["matcher_head"], converters: ["converter_string_match"] } })

" https://github.com/atusy/ddc-filter-converter_string_match
" main branch replaces items in place, and copy branch uses deepcopy of items, but the both results in the issued problem
call ddc#custom#patch_global("filterParams", #{converter_string_match: #{regexp: "\\S+$"}})


call ddc#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. prepare a following buffer

```
aba aba
aba abaa
aba abb
```

3. in a newline, insert `aba`
4. **should match to all the lines prepared in 1, but only the first two appears as a candidate.**
5. `<Down><Down><CR>` will complete `abaa` because `converter_string_match` converts the word to the last word in the line.

## Screenshot (if possible)

![image](https://github.com/Shougo/ddc.vim/assets/30277794/1b3b64cf-d24b-4e0c-b42a-1e7cb2ca08d7)

## Upload the log messages by `:redir` and `:message` (if errored)

no errors

**Comment by Shougo** [comment]
Fixed.
