### ISSUE TITLE
Feature request: raise warning when `ddc#enable()` is called with no sources or `sourceOptions` sections are ignored

### ISSUE THREAD

**Issue by lukelbd** [Shougo/ddc.vim#139]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

Recently I updated my `.vimrc` and noticed `ddc.vim` had stopped working. It seemed like a silent failure.

I spent a long time trying to figure this out before realizing I had simply removed the `'sources'` specification in my call to `ddc#custom#patch_global(...)`. It was hard to figure out because I was still providing `patch_global(...)` with `sourceOptions` (so it seemed like everything was enabled) and there were no warning or error messages to give me hints.

# Desired behavior

I think it would help new users (and help existing users with debugging) if you raised warnings or errors in either or both of the following situations:

1. Zero sources were specified
2. Source options are ignored (due to a typo, or when the corresponding source is not specified)

Thanks for the awesome plugin and all your hard work

## Environment Information

- ddc.vim version (SHA1): n/a

- denops.vim version (SHA1): n/a

- deno version(`deno -V` output): n/a

- OS: n/a

- neovim/Vim `:version` output: n/a

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Your minimal init.vim/vimrc
  set runtimepath+=~/.vim/plugged/ddc.vim/
  set runtimepath+=~/.vim/plugged/ddc-buffer/
  set runtimepath+=~/.vim/plugged/ddc-source-around/
  let s:ddc_sources = ['around', 'buffer']
  let s:ddc_options = {
    \   'around': {
    \     'mark': 'A',
    \     'maxItems': 5,
    \   },
    \   'buffer': {
    \     'mark': 'B',
    \     'maxItems': 5,
    \   },
" call ddc#custom#patch_global('sources', s:ddc_sources)  " specifying no sources does not raise warning
call ddc#custom#patch_global(s:ddc_options)  " options without sources does not raise warning
call ddc#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Open vim
1. Enable ddc

**Comment by Shougo** [comment]
Sorry.  I don't add the feature.
ddc.vim should work as user configured.

ddc.vim does not know the sources empty as expected.

**Comment by Shougo** [comment]
> I think it would help new users (and help existing users with debugging) if you raised warnings or errors in either or both of the following situations:

it is very kind feature.  But I don't think ddc.vim should be kindness for new users.

**Comment by lukelbd** [comment]
> I don't think ddc.vim should be kind for new users.

😂 Fair enough.

**Comment by Shougo** [comment]
Note: ddc.vim can detect option names typo.
