### ISSUE TITLE
`PumClose` does not fire when reopening pum ui by `forceCompletionPattern`

### ISSUE THREAD

**Issue by uga-rosa** [Shougo/ddc.vim#145]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

SSIA

## Expected

Fire `PumClose`.

## Environment Information

- ddc.vim version (SHA1): latest

- denops.vim version (SHA1): latest

- deno version(`deno -V` output): latest

- OS: ubuntu

- neovim/Vim `:version` output: NVIM v0.10.0-dev-eae6727

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=/path/to/denops.vim
set runtimepath+=/path/to/ddc.vim
set runtimepath+=/path/to/ddc-ui-pum
set runtimepath+=/path/to/pum.vim
set runtimepath+=/path/to/ddc-filter-matcher_head

call ddc#custom#patch_global(#{
      \ ui: 'pum',
      \ sources: ['test'],
      \ sourceOptions: #{
      \   _: #{
      \     minAutoCompleteLength: 1,
      \     forceCompletionPattern: '\.',
      \     matchers: ['matcher_head'],
      \   },
      \ },
      \})

inoremap <C-n> <Cmd>call pum#map#insert_relative(+1, 'loop')<CR>
inoremap <C-p> <Cmd>call pum#map#insert_relative(-1, 'loop')<CR>
inoremap <CR> <Cmd>call pum#map#confirm()<CR>

call ddc#enable()

augroup my-ddc
  au!
  au User PumClose echom 'close!'
  au User PumCompleteDone echom 'complete done!'
augroup END
```

- `denops/@ddc-sources/test.ts`
```typescript
import { BaseSource, DdcGatherItems } from "https://deno.land/x/ddc_vim@v4.0.4/types.ts";

type Params = Record<PropertyKey, never>;

export class Source extends BaseSource<Params> {
  gather(): Promise<DdcGatherItems> {
    return Promise.resolve([
      { word: "test1" },
      { word: "test2" },
    ]);
  }

  params(): Params {
    return {};
  }
}
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Input `t.`.
2. The UI should be closed and reopened, but `PumClose` is not firing.
3. After returning to normal mode, I checked with `:mes` and there is only one `close!` when closed with `InsertLeave`.

## Screenshot (if possible)

![force](https://github.com/Shougo/ddc.vim/assets/82267684/72bc82dc-f954-4c0b-8fa5-d475c723700d)

**Comment by Shougo** [comment]
Reproduced.  It is bug.

**Comment by Shougo** [comment]
Fixed.
