### ISSUE TITLE
disable highlight of info

### ISSUE THREAD

**Issue by chunxuan-hs** [Shougo/ddc.vim#149]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**
How to disable hightligh in the poppup wimdow.

# Problems summary
complete popup windows highlight info of items, and I would like to disable highlight.
See the screen shot, some info are highlighted in light cyan (e.g., snippet). 

<img width="441" alt="Screenshot 2024-01-30 at 10 25 15" src="https://github.com/Shougo/ddc.vim/assets/132476141/69dd6aa1-e655-4bd3-9548-0b2f6fc58807">

## Expected
The highlight is introduced recently and I would like to disable color highlight

## Environment Information

- ddc.vim version (SHA1):
latest
- denops.vim version (SHA1):
latest
- deno version(`deno -V` output):
deno 1.39.1
- OS:
macos

- neovim/Vim `:version` output:
```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.4/share/nvim"
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/ddc.vim/
call ddc#custom#patch_global('ui', 'native')
call ddc#custom#patch_global('sources', ['buffer', 'vsnip', 'file', 'lsp', 'rg', 'mocword'])
call ddc#custom#patch_global('sourceOptions', {
  \ '_': {
  \   'matchers': ['matcher_fuzzy', 'matcher_length'],
  \   'converters': ['converter_truncate', 'converter_remove_overlap'],
  \   'sorters': ['sorter_rank'],
  \   'minAutoCompleteLength': 1,
  \   'ignoreCase': v:true},
  \ 'lsp': {
  \   'matchers': ['matcher_fuzzy'],
  \   'mark': 'L',
  \   'minAutoCompleteLength': 2,
  \   'forceCompletionPattern': '\.\w*|:\w*|->\w*',
  \   'isVolatile': v:true},
  \ 'buffer': {
  \   'mark': 'B'},
  \ 'vsnip': {
  \   'matchers': ['matcher_fuzzy'],
  \   'dup': v:true,
  \   'mark': 'V'},
  \ 'file': {
  \   'mark': 'F',
  \   'matchers': ['matcher_full_fuzzy'],
  \   'dup': v:true,
  \   'isVolatile': v:true,
  \   'forceCompletionPattern': '\S/\S*'},
  \ 'rg': {
  \   'mark': 'R',
  \   'minAutoCompleteLength': 3},
  \ 'mocword': {
  \   'mark': 'M',
  \   'minAutoCompleteLength': 3}
  \ })

call ddc#enable()
```

**Comment by Shougo** [comment]
Well, it seems from neovim native feature.

**Comment by Shougo** [comment]
`:help hl-PmenuKind`

Please change the highlight.

**Comment by chunxuan-hs** [comment]
Thanks for the ideas, rose-pine changed the color.
