### ISSUE TITLE
Unwanted closure of popup menu on manual completion

### ISSUE THREAD

**Issue by phgz** [Shougo/ddc.vim#150]
# Problems summary
Since b2347fe, I cannot trigger manual completion. It flickers, then close.

## Expected
The popup menu appears and stay still.

## Environment Information
Everything is latest version.

Here is the behaviour:

https://github.com/Shougo/ddc.vim/assets/22773951/bb1159b2-ee51-4ad9-9a17-b59c91bd6c25

I checked the commit and it seems to basically do the same thing differently. Before giving minimal init, do you have an idea what could cause that? Otherwise I will create one as soon as I have time.

Thanks!

**Comment by Shougo** [comment]
> I checked the commit and it seems to basically do the same thing differently. Before giving minimal init, do you have an idea what could cause that? Otherwise I will create one as soon as I have time.

Please create the minimal vimrc.  If not, I close the issue.

**Comment by Shougo** [comment]
Fixed.

**Comment by phgz** [comment]
Here is

minimal.vim
```vim
set rtp+=~/denops.vim
set rtp+=~/ddc.vim
set rtp+=~/ddc-ui-native
set rtp+=~/ddc-ui-inline
set rtp+=~/ddc-source-around

set completeopt=menuone,noinsert,noselect

call ddc#custom#load_config(expand('~/ddc.ts'))
call ddc#enable()

inoremap <silent> <expr> <S-Tab> pumvisible() ? '<up>' : ddc#map#manual_complete(#{sources: ['around'], ui: 'native'})
inoremap <silent> <expr> <Tab> pumvisible() ? '<down>' : '<tab>'
inoremap <silent> <expr> <esc> pumvisible() ? '<c-e>' : '<esc>'
inoremap <silent> <expr> <cr> pumvisible() ? '<c-y>' : '<cr>'
```

ddc.ts
```ts
import { BaseConfig } from "https://deno.land/x/ddc_vim@v4.3.1/types.ts";
import { ConfigArguments } from "https://deno.land/x/ddc_vim@v4.3.1/base/config.ts";

export class Config extends BaseConfig {
  override config(args: ConfigArguments): Promise<void> {
    args.contextBuilder.patchGlobal({
      ui: "inline",
      sources: ["around"],
      autoCompleteEvents: [
        "InsertEnter",
        "TextChangedI",
        "TextChangedP",
      ],
      sourceOptions: {
        _: {
          minAutoCompleteLength : 1,
        },
      },
      backspaceCompletion: true,
    });
  }
}
```

To reproduce:

1. `nvim -u minimal.vim minimal.vim`
2. Go to empty line, start insert mode
3. Type `s` (should have inline suggestion)
4. Type `<S-tab>` (should open popup menu, but closes instantaneously)

**Comment by Shougo** [comment]
Please test the latest version.

**Comment by phgz** [comment]
It now works! Thanks for the quick fix :)
