### ISSUE TITLE
A recent update broke ddc, possibly dependency issue?

### ISSUE THREAD

**Issue by JoseGRuiz** [Shougo/ddc.vim#152]
# Problems summary
I recently did a system update and using Lazy I also updated my nvim plugins. And suddenly I started receiving error messages like the one posted at the end. I am a programmer but don't really know typescript or deno/denops. However I was able to solve the problem using a bit of guesswork and trial and error. In the end i used these commands to update deno:
```
deno add @lambdalisue/async
deno add @std/async
deno add @std/assert
deno add @std/internal
```
 and it seemed to provide files that seemed to be missing. I'm assuming there is some error in specifying dependencies but I could be wrong. Again this was discovered by trial and error so I may have done an unnecessary step or I might not have completely fixed the issue. However, for now ddc seems to be working and I get no error messages. 
## Expected
I open nvim and there are no errors and I can autocomplete using ddc. 
## Environment Information

- ddc.vim version (SHA1): e9342a9b24fc7d5b08408ae5b01f15fb3d843f2f

- denops.vim version (SHA1): [9dd9ae9da9b8d65916dd44e0e4d881665397de63](https://github.com/vim-denops/denops.vim/commit/9dd9ae9da9b8d65916dd44e0e4d881665397de63)

- deno version(`deno -V` output): deno 1.43.6

- OS: Arch Linux

- neovim/Vim `:version` output:
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478

## Provide a minimal init.vim/vimrc without plugin managers (Required!)
I included what I believe to be the relevant config from **init.lua** and the entirety of **ddc-conf.lua**
**init.lua**
```
...
local capabilities = require("ddc_source_lsp").make_client_capabilities()
require("lspconfig").denols.setup({
  capabilities = capabilities,
})

local lspconfig = require('lspconfig')
lspconfig.jedi_language_server.setup{}
lspconfig.clangd.setup{}
...
require('ddc-conf')
...
```
**ddc-conf.lua**
```
vim.call('ddc#custom#patch_global', {
-- You must set the default ui.
-- Note: native ui
-- https://github.com/Shougo/ddc-ui-native
  ui = 'native',
-- Customize global settings for ddc
-- Use around source.
-- https://github.com/Shougo/ddc-around
sources = {'around', 'lsp'},
backspaceCompletion = true,
--completionMenu = {'pum.vim'},
-- Use matcher_head and sorter_rank.
-- https://github.com/Shougo/ddc-matcher_head
-- https://github.com/Shougo/ddc-sorter_rank
sourceOptions = {
       ['_'] = {
         matchers = {'matcher_head'},
         sorters = {'sorter_rank'},
       },
      -- Change source options
       around = {
         mark = 'A',
         minAutoCompleteLength = 3
       },
       ['lsp'] = {
         mark = 'lsp',
         ignoreCase = 'true',
         --forceCompletionPattern = '\\.w*|:w*|->w*',
         forceCompletionPattern = '\\.|:|->',
       }
     },
sourceParams = {
       around = {
         maxSize = 50
       },
    ['lsp'] = {
      -- Use Customized labels
        kindLabels = { Class = 'c' },
        maxSize = 50,
        confirmBehavior = {'replace'},
    }
  }
})

-- <TAB>: completion.
vim.keymap.set('i', '<TAB>', function()
    if vim.fn.pumvisible() ~= 0 then
      return "<C-n>"
    else
      return "<TAB>"
    end
end, {silent = true, expr = true})

-- <S-TAB>: completion back.
vim.keymap.set('i', '<S-TAB>', function()
  if vim.fn.pumvisible() ~= 0 then
    print('c-p')
    return '<C-p>' 
  end
end, {expr = true})
-- close preview window when leaving insert or completion is done
vim.api.nvim_create_autocmd({'InsertLeave','CompleteDone'},
{pattern = '*',
callback = function() if vim.fn.pumvisible() == 0 then vim.cmd.pclose() end end})

-- Use ddc.
vim.fn['ddc#enable']()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. open nvim 
2. message at the bottom says `[denops]     at async Lock.lock (https://jsr.io/@lambdalisue/async/2.1.1/lock.ts:51:14)`

3. dcc autocomplete doesn't work

## Upload the log messages by `:redir` and `:message` (if errored)
This message was repeated after every `deno add` command and I used it to guide me as to what to install.
[denops] Failed to handle message 2,invoke,dispatch,ddc,onEvent,Initialize TypeError: Could not find constraint in the list of versions: @std/internal@^1.0.0
[denops]   Specifier: jsr:/@std/internal@^1.0.0/format
[denops]     at https://jsr.io/@std/assert/0.225.3/assert_not_strict_equals.ts:4:24
[denops]     at async Loader.#register (file:///home/jose/.local/share/nvim/lazy/ddc.vim/denops/ddc/loader.ts:140:7)
[denops]     at async file:///home/jose/.local/share/nvim/lazy/ddc.vim/denops/ddc/loader.ts:112:7
[denops]     at async Lock.lock (https://jsr.io/@lambdalisue/async/2.1.1/lock.ts:51:14)
[denops]     at async Loader.registerPath (file:///home/jose/.local/share/nvim/lazy/ddc.vim/denops/ddc/loader.ts:111:5)
[denops]     at async Loader.autoload (file:///home/jose/.local/share/nvim/lazy/ddc.vim/denops/ddc/loader.ts:103:5)
[denops]     at async getSource (file:///home/jose/.local/share/nvim/lazy/ddc.vim/denops/ddc/ext.ts:122:5)
[denops]     at async onEvent (file:///home/jose/.local/share/nvim/lazy/ddc.vim/denops/ddc/ext.ts:350:51)
[denops]     at async _onEvent (file:///home/jose/.local/share/nvim/lazy/ddc.vim/denops/ddc/app.ts:288:5)
[denops]     at async file:///home/jose/.local/share/nvim/lazy/ddc.vim/denops/ddc/app.ts:214:11
[denops]     at async Lock.lock (https://jsr.io/@lambdalisue/async/2.1.1/lock.ts:51:14)

**Comment by Shougo** [comment]
It is Deno's cache bug.  You need to rebuild cache like this.

`deno cache --reload ddc.vim/denops/ddc/deps.ts`

**Comment by jchain** [comment]
I was bothered by this issue for weeks. Thank you so much for giving the solution above. I think you should list that solution in `README.md`

**Comment by Shougo** [comment]
@jchain The latest denops.vim detects the error and prints more detailed information.
So I don't update the documentation.

**Comment by jchain** [comment]
<img width="1475" alt="image" src="https://github.com/Shougo/ddc.vim/assets/814893/9462ab8d-673c-47ff-8fab-0de28870f66d">
I update ddc.vim and your other plugins frequently. Above is the error message that had bothered me. As a deno noob, I had no clue how to solve it. It is your call to whether update the readme or not. I comment here to help others to locate the error/solution.

**Comment by Shougo** [comment]
Please see this.

https://github.com/vim-denops/denops.vim/pull/359

It is one hour ago changes.
