### ISSUE TITLE
If I run :Calculator immediately after starting Vim, I will see ‘[ddc] Not found ui: “pum”’.

### ISSUE THREAD

**Issue by hokorobi** [Shougo/ddc.vim#157]
# Problems summary
If I run :Calculator immediately after starting Vim, I will see ‘[ddc] Not found ui: “pum”’.

## Expected
The ‘[ddc] Not found ui: “pum”’ is not displayed.

## Environment Information

- ddc.vim version (SHA1): 
1ff3843c

- denops.vim version (SHA1):
ce5d2904

- deno version(`deno -V` output):
1.46.3

- dein.vim version (SHA1):
000487e

- OS:
Windows11

- Vim `:version` output:
`VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Sep 26 2024 22:13:06)
MS-Windows 64 ビット GUI/コンソール 版 with OLE サポート
適用済パッチ: 1-744
Compiled by appveyor@APPVEYOR-VM
Huge 版 with GUI.  機能の一覧 有効(+)/無効(-)
+acl                +cindent            +cursorshape        -farsi              +job                +menu               +packages           +reltime            -sun_workshop       -tgetent            +visualextra        -xterm_save
+arabic             +clientserver       +dialog_con_gui     +file_in_path       +jumplist           +mksession          +path_extra         +rightleft          +syntax             +timers             +vreplace           
+autocmd            +clipboard          +diff               +find_in_path       +keymap             +modify_fname       +perl/dyn           +ruby/dyn           +tag_binary         +title              +vtp                
+autochdir          +cmdline_compl      +digraphs           +float              +lambda             +mouse              +persistent_undo    +scrollbind         -tag_old_static     +toolbar            +wildignore         
+autoservername     +cmdline_hist       +directx            +folding            +langmap            +mouseshape         +popupwin           +signs              -tag_any_white      +user_commands      +wildmenu           
+balloon_eval       +cmdline_info       -dnd                -footer             +libcall            +multi_byte_ime/dyn -postscript         +smartindent        -tcl                +vartabs            +windows            
+balloon_eval_term  +comments           -ebcdic             +gettext/dyn        +linebreak          +multi_lang         +printer            +sodium/dyn         +termguicolors      +vertsplit          +writebackup        
+browse             +conceal            +emacs_tags         -hangul_input       +lispindent         +mzscheme/dyn       +profile            +sound              +terminal           +vim9script         -xattr              
++builtin_terms     +cryptv             +eval               +iconv/dyn          +listcmds           +netbeans_intg      +python/dyn         +spell              -termresponse       +viminfo            -xfontset           
+byte_offset        +cscope             +ex_extra           +insert_expand      +localmap           +num64              +python3/dyn-stable +startuptime        +textobjects        +virtualedit        -xim                
+channel            +cursorbind         +extra_search       +ipv6               +lua/dyn            +ole                +quickfix           +statusline         +textprop           +visual             +xpm_w32            
      システム vimrc: "$VIM\vimrc"
      ユーザー vimrc: "$HOME\_vimrc"
   第2ユーザー vimrc: "$HOME\vimfiles\vimrc"
   第3ユーザー vimrc: "$VIM\_vimrc"
       ユーザー exrc: "$HOME\_exrc"
    第2ユーザー exrc: "$VIM\_exrc"
     システム gvimrc: "$VIM\gvimrc"
     ユーザー gvimrc: "$HOME\_gvimrc"
  第2ユーザー gvimrc: "$HOME\vimfiles\gvimrc"
  第3ユーザー gvimrc: "$VIM\_gvimrc"
  デフォルトファイル: "$VIMRUNTIME\defaults.vim"
    システムメニュー: "$VIMRUNTIME\menu.vim"
コンパイル: cl -c /W3 /GF /nologo -I. -Iproto -DHAVE_PATHDEF -DWIN32 -DHAVE_STDINT_H  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_INTG   -DFEAT_XPM_W32 -DHAVE_SODIUM -DDYNAMIC_SODIUM -DDYNAMIC_SODIUM_DLL=\"libsodium.dll\" /I "C:\projects\vim-win32-installer\dependencies\libsodium\include" -DFEAT_JOB_CHANNEL -DFEAT_IPV6 -DHAVE_INET_NTOP -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 /source-charset:utf-8 /MP /Ox /GL -DNDEBUG /Zl /MT -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -DVIMDLL -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua54.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python3.dll\" -DDYNAMIC_PYTHON3_STABLE_ABI -DFEAT_MZSCHEME -I "C:\projects\vim-win32-installer\dependencies\racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_dcgt6o.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_dcgt6o.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl532.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64-ucrt-ruby320.dll\" -DRUBY_VERSION=32 -DFEAT_HUGE /Fd.\ObjDXOULYHRZAMD64/ /Zi
リンク: link /nologo /opt:ref /LTCG /HIGHENTROPYVA:NO oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib user32.lib  /machine:AMD64 version.lib  winspool.lib comctl32.lib libcmt.lib oleaut32.lib  /nodefaultlib:lua54.lib  /STACK:8388608  /nodefaultlib:python27.lib  /nodefaultlib:python3.lib   winmm.lib  Ws2_32.lib xpm\x64\lib-vc14\libXpm.lib  /PDB:vim64.pdb -debug
`

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

vimrc-min
```vim
set rtp+=~/_vim/dein/repos/github.com/Shougo/dein.vim
if dein#min#load_state('~/_vim/dein')
  call dein#begin('~/_vim/dein')
  call dein#load_toml('~/vimfiles/vimrc-min.toml')
  call dein#end()
  call dein#save_state()
endif
filetype plugin indent on
syntax enable
```

vimrc-min.toml
```toml
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = 'denops.vim'
on_event = 'InsertEnter'
hooks_file = '~/vimfiles/vimrc-min.vim'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_source = 'ddc.vim'
depends = 'pum.vim'

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'fedorenchik/calculator.vim'
on_cmd = 'Calculator'
```

vimrc-min.vim
```vim
" hook_source {{{
let s:ddc_sourceOptions = {}
let s:ddc_sourceOptions['_'] = #{
    \   matchers: ['matcher_head'],
    \   sorters: ['sorter_rank'],
    \ }
let s:ddc_options = #{
    \   sourceOptions: s:ddc_sourceOptions,
    \   ui: 'pum',
    \ }
call ddc#custom#patch_global(s:ddc_options)

call ddc#custom#patch_filetype(
    \ ['vim'],
    \ #{sources: ['around']})
call ddc#enable()
" }}}
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `gvim -N -u ~/vimfiles/vimrc-min -U NONE -i NONE`
2. `:call dein#recache_runtimepath()`
3. `:q`
4. `gvim -N -u ~/vimfiles/vimrc-min -U NONE -i NONE`
5. `:Calculator`
6. It appears like Screenshot.

## Screenshot (if possible)
![image](https://github.com/user-attachments/assets/764df568-29dd-475f-9b05-5e6f95e07086)

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
Fixed.

**Comment by hokorobi** [comment]
Thank you!
