### ISSUE TITLE
[Request] Ability to close pop-up

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/ddc.vim#28]
Thank you for creating this plugin.
I made an issue because I wanted to request one function.

## Expected
I want the function to close the pop-up that existed in 'deoplete'.

## Environment Information
 * ddc version (SHA1): eab78cbfe76f877b14fc84a76c75b3cf530098e4

**Comment by nabezokodaikon** [comment]
The reason is that when the pop-up is decided by the enter key, a line break occurs.

**Comment by Shougo** [comment]
Why you cannot use `<C-y>`?  Please describe the example.

**Comment by nabezokodaikon** [comment]
I didn't know about <C-y>. sorry.

**Comment by Shougo** [comment]
OK.  If the feature is really needed, I will add it.
