### ISSUE TITLE
user_data of complete() is not passed to Vim.

### ISSUE THREAD

**Issue by matsui54** [Shougo/ddc.vim#31]
Vim's complete item accepts user_data, which is snake case, but in ddc, user data is defined as camel case like [this](https://github.com/Shougo/ddc.vim/blob/80c5f2e792ccea1c8582759c026c9b5e957c6eb4/denops/ddc/types.ts#L66). Because of this mismatch of name, user_data is not passed to Vim.

Converting Candidates' userData to user_data or changing Candidate's type is needed.

**Comment by Shougo** [comment]
Thanks.  Fixed.

**Comment by matsui54** [comment]
Thanks. Can you update the ddc version?

**Comment by Shougo** [comment]
OK.  I will do it later.

**Comment by Shougo** [comment]
Done.

**Comment by matsui54** [comment]
Thanks. Please see https://github.com/Shougo/ddc-nvim-lsp/pull/6
