### ISSUE TITLE
Exception during denops#notify: `TextChangedI Autocommands for "*"..function`

### ISSUE THREAD

**Issue by takavfx** [Shougo/ddc.vim#40]
# Problems summary

When enabling ddc, after hitting some words then ddc outputs errors during `denops#server#notify` .
I checked denops iteself worked without troubles.

## Error output

```
TextChangedI Autocommands for "*"..function denops#notify[1]..denops#server#notify[2]..TextChangedI Autocommands for "*"..function denops#notify[1]..denops#server#notify の処理中にエラーが検出されました:
行    2:
E605: 例外が捕捉されませんでした: The server is not ready yet
```

## Expected

I'm quite new to the vim area. Any trouble shoot guides are quite helpful. Thank you.

## Environment Information

 * ddc version (SHA1): 0.4

 * OS: Windows 10

 * neovim/Vim `:version` output:  Vim 8.2

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" I use dein installation to get ddc

call ddc#custom#patch_global('sources', ['around'])

call ddc#custom#patch_global('sourceOptions', {
			\ '_': {
			\   'matchers': ['matcher_head'],
			\   'sorters': ['sorter_rank'],},
			\ })

inoremap <silent><expr> <TAB>
			\ pumvisible() ? '<C-n>' :
			\ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
			\ '<TAB>' : ddc#manual_complete()

inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'

call ddc#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Install ddc and dependencies. (Install also ddc-around, ddc-matcher_head, ddc-sorter_rank)
 2. Type settings into .vimrc like above.
 3. Enabling ddc with `call ddc#enable()` (Before enabling, any errors is not output)

## Screenshot (if possible)

![image](https://user-images.githubusercontent.com/7938883/131427393-d81c7fd2-7da3-438e-9c31-d3b3ff8e8625.png)

**Comment by Shougo** [comment]
I get the problem.  It is bug.

**Comment by Shougo** [comment]
Fixed.  Please test the latest.

**Comment by takavfx** [comment]
Thank you! I also confirmed that's already fixed!
