### ISSUE TITLE
Can onInit() have sourceParams?

### ISSUE THREAD

**Issue by delphinus** [Shougo/ddc.vim#42]
# Problems summary

`onInit()` does not have `sourceParams` in arguments.

## Expected

`onInit()` can have `sourceParams` in arguments.

## Detail

I am writing [ddc-ctags][] and want to add a feature to specify a path to `ctags` executable. There are several kinds of “Ctags”'s, but the latest Universal Ctags is the one I want to use in this plugin.

[ddc-ctags]: https://github.com/delphinus/ddc-ctags

So I need to test the executable the user set in `sourceParams`, but it is annoying that it runs tests every time `gatherCandidates()` is called.

If `onInit()` can have `sourceParams`, it needs to test only once.

**Comment by Shougo** [comment]
I have changed `onInit()` arguments.
Please update ddc.vim to the latest.
