### ISSUE TITLE
[Development question] Is apiVersion a public interface?

### ISSUE THREAD

**Issue by delphinus** [Shougo/ddc.vim#44]
I found each filer & source succeeds the `apiVersion` property. Can plugin authors use this to show warnings when the user is using old ddc.vim?

For instance, I want to use updated `onInit()` that has `sourceParams` in its arguments. Can I warn when `apiVersion < 2`, that is, no `sourceParams` in arguments?

```typescript
onInit({ sourceParams }: OnInitArguments) {
  if (this.apiVersion < 3) {
    some_warning_func('Use ddc.vim >=0.5.0')
    return
  }
  ...
}
```

**Comment by Shougo** [comment]
Sorry.  The attribute is for internal use to compatible check.
And the source cannot use it because the source imports newer `BeseSource` and it may be newer than current ddc version's `BaseSource`.

**Comment by Shougo** [comment]
If you want to check the old version, you should check `sourceParams` is `undefined` instead.
