### ISSUE TITLE
[Enhance] add floating preview window feature support to vim

### ISSUE THREAD

**Issue by krisfans** [Shougo/ddc.vim#47]
# Problems summary
Are you consider adding floating preview window feature support to vim to show snippet and hook information, just like coc.nvim?
Or create a new plugin to implement this feature both work on nvim and vim ? I noticed that both ddc.vim and coc.nvim are plugins based on ts scripts. Does this make it possible to increase floating windows feature for vim ?

**Comment by Shougo** [comment]
https://github.com/matsui54/ddc-nvim-lsp-doc

The plugins exists for nvim-lsp floating preview information.

I don't add the feature in ddc.vim.  Because it should be implemented in other plugin.

I don't interest the feature.  So I don't create new plugin...
