### ISSUE TITLE
Omni source ?

### ISSUE THREAD

**Issue by krillin666** [Shougo/ddc.vim#48]
Hello,

Is it possible to use Omni sources with ddc ? I was previously using Deoplete with Vimtex autocompletion, but wanted to move to ddc now, since it is being maintained.

Thank you !

**Comment by Shougo** [comment]
Well.  To add omni source is possible.  But it is hard to maintain.

**Comment by matsui54** [comment]
@krillin666 If you use LSP, [texlab](https://github.com/latex-lsp/texlab) is a very good alternative to Vimtex omnifunc. It works asynchronously and doesn't block Vim.
It also doesn't conflict with Vimtex.

**Comment by Shougo** [comment]
https://github.com/Shougo/ddc-omni

Please wait...

**Comment by Shougo** [comment]
I have added.

```vim
call vimtex#init()
call ddc#custom#patch_filetype(['tex'], 'sourceOptions', {
      \ 'omni': {'mark': 'O', 'forceCompletionPattern': g:vimtex#re#deoplete},
      \ })
call ddc#custom#patch_filetype(['tex'], 'sourceParams', {
      \ 'omni': {'omnifunc': 'vimtex#complete#omnifunc'},
      \ })
```
