### ISSUE TITLE
`.` does not repeat insertion for `indentkeys`

### ISSUE THREAD

**Issue by e-kwsm** [Shougo/ddc.vim#51]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Repetition `.` does not work if a user inserts a ddc completion word that contains&mdash;or in this case starts with&mdash;`indentkeys`, e.g., `\bibitem` and `\item` for tex, see [runtime/indent/tex.vim#L153](https://github.com/neovim/neovim/blob/4881456e83fb49994677fe06aef3b0c597ba4517/runtime/indent/tex.vim#L153) and [runtime/indent/tex.vim#L168](https://github.com/neovim/neovim/blob/4881456e83fb49994677fe06aef3b0c597ba4517/runtime/indent/tex.vim#L168).

This bisects to 58c68543f99996fa7ae088391a48e02c63e3aa55.

## Expected
`.` works, i.e. repeats insertion.

## Environment Information

 * ddc.vim version (SHA1): 5b4dd563fe0e0707a03ee93021927e59c17bbc32

 * denops.vim version (SHA1): vim-denops/denops.vim@4b7d2298f8691d25e3550d360f8f1175915c40eb

 * deno version(`deno -V` output): 1.14.0

 * OS: Debian 11.0

 * neovim/Vim `:version` output: NVIM v0.6.0-dev+286-g4881456e8

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#lsp#check
========================================================================
## Checking language server client configuration
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/kwsm/.cache/nvim/lsp.log
  - INFO: Log size: 0 KB

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6203'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help |clipboard|

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          python not found in search path or not executable.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.9.2
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

health#treesitter#check
========================================================================
## Checking treesitter configuration
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for c: ABI version 13

health#denops#check
========================================================================
  - INFO: Supported Deno version: `1.11.0`
  - INFO: Detected Deno version: `1.14.0`
  - OK: Deno version check: passed
  - INFO: Supported Neovim version: `0.4.4`
  - INFO: Detected Neovim version: `0.6.0`
  - OK: Neovim version check: passed
  - INFO: Denops status: `running`
  - OK: Denops status check: passed
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath-=~/.config/nvim
set runtimepath-=~/.config/nvim/after
set runtimepath-=~/.local/share/nvim/site
set runtimepath-=~/.local/share/nvim/site/after

set runtimepath+=/path/to/ddc.vim
set runtimepath+=/path/to/denops.vim

call ddc#register_source({'name': 'tex', 'path': '/tmp/tex.ts',})
call ddc#custom#patch_filetype('tex', 'sources', ['tex'])

call ddc#enable()
```

Register the following source:

```typescript
// /tmp/tex.ts
import {
  BaseSource,
  Candidate,
} from "https://deno.land/x/ddc_vim@v0.6.0/types.ts#^";
import { GatherCandidatesArguments } from "https://deno.land/x/ddc_vim@v0.6.0/base/source.ts#^";

export class Source extends BaseSource {
  async gatherCandidates(
    _args: GatherCandidatesArguments,
  ): Promise<Candidate[]> {
    return [
      { word: "\\large" }, // this works
      { word: "\\item" }, // this doesn't
    ];
  }
}
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. `nvim -u vimrc -c 'setf tex' - <<< '  foo'`
 2. `I\large <ESC>...` &mdash;works as expected
 3. `I\item <ESC>...` &mdash;does not work

## Screenshot (if possible)
5b4dd563fe0e0707a03ee93021927e59c17bbc32:
![5b4dd56](https://user-images.githubusercontent.com/11627708/133773159-c1993653-3443-4043-a8bc-61de2393b7db.gif)

e74e9198e73248d2b9cfd936a3aa3e2678447f21 (= 58c68543f99996fa7ae088391a48e02c63e3aa55^):
![e74e919](https://user-images.githubusercontent.com/11627708/133773171-8cc10597-bb91-4051-b4c6-0654b2f5c746.gif)

`NORC`:
![NORC](https://user-images.githubusercontent.com/11627708/133773579-21f18c70-643c-44f8-92ba-190427f172fd.gif)

**Comment by Shougo** [comment]
Sorry.  I cannot fix the problem.  Because it is needed for indentkeys support.
If I remove the feature, `\item` is not indented!

I don't have the perfect solution.  Please provide better solution instead.

**Comment by Shougo** [comment]
It seems fixed.  Please test the latest version.

**Comment by e-kwsm** [comment]
Thank you for your quick fix.

**Comment by e-kwsm** [comment]
BTW
https://github.com/Shougo/ddc.vim/blob/e65f4a4e7d840bbde3115feeaca2e2a3cdafc2fc/.github/ISSUE_TEMPLATE.md#L15
should be `deno -V` (at least deno 1.14.0 denies lower `-v`).

**Comment by Shougo** [comment]
Thanks. I have fixed.
