### ISSUE TITLE
ddc#disable_cmdline_completion() is fail when cmdline is empty

### ISSUE THREAD

**Issue by 4513ECHO** [Shougo/ddc.vim#80]
# Problems summary

`ddc#disable_cmdline_completion()` is fail when cmdline is empty

## Environment Information

- ddc.vim version (SHA1):

`51995c851b470cbca801f44a41c6f28a6b1a0f65`

- denops.vim version (SHA1):¬

`228d446132825bd8035a5530a206611f639f9a74`

- deno version(`deno -V` output):

`deno 1.16.3`

- OS:

`Ubuntu 21.04`

- neovim/Vim `:version` output:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec  3 2021 08:00:46)
適用済パッチ: 1-3724
Compiled by Hibiki <4513echo@gmail.com>
Huge 版 without GUI.  機能の一覧 有効(+)/無効(-)
```

- `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
if &compatible
  set nocompatible
endif
autocmd!

set runtimepath+=/path/to/repos/github.com/vim-denops/denops.vim
set runtimepath+=/path/to/repos/github.com/Shougo/ddc.vim

function! s:ddc_cmdlime_pre() abort
  autocmd User DDCCmdlineLeave ++once call s:ddc_cmdlime_post()
  call ddc#enable_cmdline_completion()
endfunction

function! s:ddc_cmdlime_post() abort
  call ddc#disable_cmdline_completion()
endfunction

autocmd CmdlineEnter : call s:ddc_cmdlime_pre()

call ddc#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Type `:`
2. Type `<BS>`

## Screenshot (if possible)

![5E9414B3-7538-45B8-9263-18E239BC7F95](https://user-images.githubusercontent.com/81011153/144993082-d38fa533-03aa-4eff-8de8-076d094ddce6.jpeg)

**Comment by 4513ECHO** [comment]
I think, it will fix this problem.

```diff
function! ddc#_clear_inline() abort
  if exists('*nvim_buf_set_virtual_text')
    if !exists('s:ddc_namespace')
      let s:ddc_namespace = nvim_create_namespace('ddc')
    endif

    call nvim_buf_clear_namespace(bufnr('%'), s:ddc_namespace, 0, -1)
-  elseif g:ddc#_inline_popup_id > 0
+  elseif exists(g:ddc#_inline_popup_id) && g:ddc#_inline_popup_id > 0
    call popup_close(g:ddc#_inline_popup_id)
  endif

  let g:ddc#_inline_popup_id = -1
endfunction
```

**Comment by Shougo** [comment]
I cannot reproduce the error though.

**Comment by Shougo** [comment]
You don't test the minimal vimrc.

```vim
 autocmd User DDCCmdlineLeave ++once call s:ddc_cmdlime_post()
```

must be `CmdlineLeave`.

**Comment by Shougo** [comment]
I get it.  It is reproduced in Vim8 only.
