### ISSUE TITLE
Invalid filters are detected issue

### ISSUE THREAD

**Issue by amadeus** [Shougo/ddc.vim#82]
# Problems summary

I've recently noticed the error:

```
[ddc] Invalid filters are detected!
[ddc] ['converter_remove_overlap', 'matcher_head', 'sorter_rank'] 
``` 

Seems to appear at the beginning of any editing session. It doesn't seem to affect anything and I don't think I have anything configured incorrectly.  Based on what I can find in the readme and help, I can't really tell what might've changed. In fact, some of these filters are still referenced in the README (i.e. sorter_rank).

## Expected

To not have the error messages, are these filters perhaps deprecated? Or are there new ways of doing things that I need to be aware of?

## Environment Information

- ddc.vim version (SHA1): 6596342

- denops.vim version (SHA1): 228d446

- deno version(`deno -V` output): deno 1.16.3

- OS: macOS 11.6

- neovim/Vim `:version` output: MacVim 8.2 patches 1-3863

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Current ddc configuration
Plug 'vim-denops/denops.vim'
Plug 'Shougo/ddc.vim'
Plug 'Shougo/pum.vim'
Plug 'Shougo/ddc-matcher_head'
Plug 'matsui54/ddc-buffer'
Plug 'statiolake/ddc-ale'
Plug 'Shougo/ddc-sorter_rank'
Plug 'Shougo/ddc-converter_remove_overlap'
Plug 'amadeus/ddc-file-source'
Plug 'LumaKernel/ddc-tabnine'
Plug 'Shougo/ddc-omni'

call ddc#custom#patch_global('sources', ['ale', 'buffer'])

call ddc#custom#patch_global('sourceOptions', {
  \ '_': {
    \ 'matchers': ['matcher_head'],
    \ 'sorters': ['sorter_rank'],
    \ 'converters': ['converter_remove_overlap'],
    \ 'minAutoCompleteLength': 1,
  \ },
  \ 'ale': {
    \ 'mark': 'lsp',
    \ 'forceCompletionPattern': '\.|:|->|\./',
  \ },
  \ 'buffer': {
    \ 'mark': 'buf',
  \ },
  \ 'file': {
    \ 'mark': 'file',
  \ },
  \ 'omni': {
    \ 'mark': 'omni',
  \ },
  \ 'tabnine': {
    \ 'mark': 'TN',
    \ 'isVolatile': v:true,
    \ 'maxSize': 200,
  \ }
\ })

call ddc#enable()
```

**Comment by Shougo** [comment]
Please use the latest ddc.vim and deno.

**Comment by amadeus** [comment]
thanks for the fix!
