### ISSUE TITLE
ctrl-e could not close completion menu

### ISSUE THREAD

**Issue by ccshao** [Shougo/ddc.vim#97]
# Problems summary
Ctrl-e could not close the completion menu

## Expected
Ctrl-e would close the completion menu. By the way, Ctrl-y selects the condidate as expected.

## Environment Information

- ddc.vim version (SHA1): latest

- denops.vim version (SHA1): latest

- deno version(`deno -V` output): deno 1.22.0

- OS: linux

- neovim/Vim `:version` output:
> NVIM v0.7.2
> Build type: RelWithDebInfo
> LuaJIT 2.1.0-beta3
> Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET
> _ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wc
> onversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthr
> ough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla
> -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DN
> VIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config
>  -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/
> runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
> Compiled by runner@fv-az395-591

- `:checkhealth` or `:CheckHealth` result(neovim only):
> denops: health#denops#check
> ========================================================================
>   - INFO: Supported Deno version: `1.17.1`
>   - INFO: Detected Deno version: `1.22.0`
>   - OK: Deno version check: passed
>   - INFO: Supported Neovim version: `0.6.0`
>   - INFO: Detected Neovim version: `0.7.2`
>   - OK: Neovim version check: passed
>   - INFO: Denops status: `running`
>   - OK: Denops status check: passed
> 
> nvim: health#nvim#check
> ========================================================================
> ## Configuration
>   - OK: no issues found
> 
> ## Performance
>   - OK: Build type: RelWithDebInfo
> 
> ## Remote Plugins
>   - OK: Up to date
> 
> ## terminal
>   - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
>   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
>   - INFO: $VTE_VERSION='5803'
>   - INFO: $COLORTERM='truecolor'
> 
> provider: health#provider#check
> ========================================================================
> ## Clipboard (optional)
>   - OK: Clipboard tool found: xclip
> 
> ## Python 3 provider (optional)
>   - INFO: Using: g:python3_host_prog = "/home/shao/miniconda3/envs/env_nvim/bin/python"
>   - INFO: Executable: /home/shao/miniconda3/envs/env_nvim/bin/python
>   - INFO: Python version: 3.8.5
>   - INFO: pynvim version: 0.4.3
>   - OK: Latest pynvim is installed.
> 
> ## Python virtualenv
>   - OK: no $VIRTUAL_ENV
> 
> ## Ruby provider (optional)
>   - INFO: Ruby: ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux-gnu]
>   - WARNING: `neovim-ruby-host` not found.
>     - ADVICE:
>       - Run `gem install neovim` to ensure the neovim RubyGem is installed.
>       - Run `gem environment` to ensure the gem bin directory is in $PATH.
>       - If you are using rvm/rbenv/chruby, try "rehashing".
>       - See :help |g:ruby_host_prog| for non-standard gem installations.
>       - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim
> 
> ## Node.js provider (optional)
>   - INFO: Node.js: v14.19.1
>   - WARNING: Missing "neovim" npm (or yarn) package.
>     - ADVICE:
>       - Run in shell: npm install -g neovim
>       - Run in shell (if you use yarn): yarn global add neovim
>       - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim
> 
> ## Perl provider (optional)
>   - WARNING: "Neovim::Ext" cpan module is not installed
>     - ADVICE:
>       - See :help |provider-perl| for more information.
>       - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim
> 
> vim.lsp: require("vim.lsp.health").check()
> ========================================================================
>   - INFO: LSP log level : WARN
>   - INFO: Log path: /home/shao/.cache/nvim/lsp.log
>   - INFO: Log size: 844 KB
> 
> vim.treesitter: require("vim.treesitter.health").check()
> ========================================================================
>   - INFO: Runtime ABI version : 14
>   - OK: Loaded parser for c: ABI version 13
> 

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
```vim
call ddc#custom#patch_global('sources', ['around', 'buffer', 'nvim-lsp', 'file', 'ultisnips'])
call ddc#custom#patch_global('sourceOptions', {
  \ '_': {
  \   'sorters': [],
  \   'converters': ['converter_truncate'],
  \   'ignoreCase': v:true},
...
  \ 'file': {
  \   'matchers': ['matcher_full_fuzzy', 'matcher_length'],
  \   'mark': 'F',
  \   'isVolatile': v:true,
  \   'forceCompletionPattern': '\S/\S*'},
  \ })

call ddc#custom#patch_global('postFilters', ["postfilter_score"])

call ddc#custom#patch_filetype(
  \ ['ps1', 'dosbatch', 'autohotkey', 'registry'], {
  \ 'sourceOptions': {
  \   'file': {
  \     'forceCompletionPattern': '\S\\\S*',
  \   }},
  \ })

call ddc#custom#patch_global('filterParams', {
  \ 'converter_truncate': {'maxAbbrWidth': 40, 'maxKindWidth':20, 'maxMenuWidth':40},
  \ })

inoremap <silent><expr> <TAB>
\ ddc#map#pum_visible() ? '<C-n>' :
\ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
\ '<TAB>' : ddc#map#manual_complete()

" <S-TAB>: completion back.
inoremap <expr><S-TAB>  ddc#map#pum_visible() ? '<C-p>' : '<C-h>'
set completeopt+=noinsert
call ddc#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)
open a file, type a few char and wait for the completion menu. ctrl-e could not close the men.

**Comment by Shougo** [comment]
Fixed.
